from flask import Flask, request, jsonify

# Create a Flask app
app = Flask(__name__)

# Mock data for 100 students (replace this with the actual data you downloaded)
student_marks = [
    {"name": "IjJOGavw", "marks": 65},
    {"name": "Ry2N2zqyxV", "marks": 74},
    {"name": "XJ", "marks": 86},
    {"name": "u4J5yg", "marks": 67},
    {"name": "wP3z", "marks": 56},
    {"name": "gZUeYtNy", "marks": 78},
    {"name": "TwoAVY", "marks": 84},
    {"name": "hjHX0da6P", "marks": 63},
    {"name": "I8h", "marks": 53},
    {"name": "Ws", "marks": 40},
    {"name": "i", "marks": 90},
    {"name": "ixowyOhi", "marks": 43},
    {"name": "DXj84bBjI", "marks": 64},
    {"name": "MdR5P", "marks": 90},
    {"name": "MiZQ", "marks": 68},
    {"name": "WAx4f", "marks": 37},
    {"name": "BYSInODP", "marks": 9},
    {"name": "hkGS5cZaZK", "marks": 93},
    {"name": "z4zP", "marks": 79},
    {"name": "ucMyNdAS4", "marks": 75},
    {"name": "tww", "marks": 15},
    {"name": "Ch", "marks": 56},
    {"name": "Iiy5Wj", "marks": 70},
    {"name": "l9aO9X4", "marks": 40},
    {"name": "jhnF", "marks": 17},
    {"name": "EA", "marks": 51},
    {"name": "t", "marks": 49},
    {"name": "RQ3Xenevzm", "marks": 80},
    {"name": "IR4BP2R", "marks": 78},
    {"name": "xDyi", "marks": 56},
    {"name": "q", "marks": 23},
    {"name": "IUtO", "marks": 57},
    {"name": "y", "marks": 54},
    {"name": "4zi5hU", "marks": 58},
    {"name": "domgQeSi", "marks": 78},
    {"name": "d", "marks": 98},
    {"name": "wMeV", "marks": 75},
    {"name": "F", "marks": 76},
    {"name": "zH", "marks": 6},
    {"name": "v", "marks": 41},
    {"name": "p1qarRV", "marks": 87},
    {"name": "Xrt", "marks": 13},
    {"name": "6sFp85", "marks": 83},
    {"name": "McnB", "marks": 45},
    {"name": "8c6rwy4H", "marks": 39},
    {"name": "qhA6", "marks": 30},
    {"name": "nwS2j3Csd", "marks": 77},
    {"name": "UtE", "marks": 87},
    {"name": "4BPN", "marks": 28},
    {"name": "K5xDJ1UnFa", "marks": 42},
    {"name": "a", "marks": 97},
    {"name": "yP", "marks": 58},
    {"name": "loI", "marks": 75},
    {"name": "vHoMag", "marks": 17},
    {"name": "hcsxa", "marks": 80},
    {"name": "qo", "marks": 43},
    {"name": "CPNDPn9vna", "marks": 8},
    {"name": "397FgT", "marks": 56},
    {"name": "uR5Kl6sgfY", "marks": 89},
    {"name": "cD", "marks": 47},
    {"name": "4", "marks": 33},
    {"name": "ASlkGZ7H", "marks": 63},
    {"name": "wu0eyAO", "marks": 77},
    {"name": "i34KXwZui", "marks": 51},
    {"name": "sn", "marks": 35},
    {"name": "91R", "marks": 5},
    {"name": "2jdn", "marks": 94},
    {"name": "ja", "marks": 15},
    {"name": "5UE", "marks": 27},
    {"name": "E7p", "marks": 57},
    {"name": "m", "marks": 55},
    {"name": "2tZ8go2j9", "marks": 85},
    {"name": "gM", "marks": 97},
    {"name": "AD5D6ZW8", "marks": 31},
    {"name": "J", "marks": 41},
    {"name": "BWgB", "marks": 7},
    {"name": "VMWF9SsR8", "marks": 94},
    {"name": "J", "marks": 0},
    {"name": "fD", "marks": 1},
    {"name": "sbCHxPxG", "marks": 49},
    {"name": "ab3b4jbKB", "marks": 81},
    {"name": "np0", "marks": 52},
    {"name": "OS32N", "marks": 59},
    {"name": "bN9EOLDA", "marks": 84},
    {"name": "l", "marks": 35},
    {"name": "SBkGk", "marks": 96},
    {"name": "HdDBJ", "marks": 59},
    {"name": "fkPW0LExI", "marks": 52},
    {"name": "FDnv", "marks": 9},
    {"name": "kd", "marks": 58},
    {"name": "C", "marks": 13},
    {"name": "j", "marks": 85},
    {"name": "RSsZM", "marks": 80},
    {"name": "Mxx61", "marks": 88},
    {"name": "YJuB", "marks": 18},
    {"name": "6Ygy", "marks": 80},
    {"name": "6jU", "marks": 14},
    {"name": "tVED", "marks": 86},
    {"name": "kh6Grolhn", "marks": 17},
    {"name": "huWX", "marks": 31},
]


@app.route("/api", methods=["GET"])
def get_marks():
    # Get the names from the query parameters
    names = request.args.getlist("name")
    # Retrieve marks for the given names
    marks = [student_marks.get(name, "Name not found") for name in names]
    # Return the JSON response
    return jsonify({"marks": marks})
